name: Run Newman Tests
on:
  schedule:
    - cron: '0 3 * * *'  # Запуск в 03:00 UTC
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman
      - run: npm install -g newman-reporter-htmlextra
      - run: newman run collections/CreateOrder.postman_collection.json -e environment/Dev.postman_environment.json -r htmlextra --reporter-htmlextra-export report.html
      - uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: report.html
